version: '3'

services:

  php:
    image: php:7.3-apache
    container_name: php_7.3
    tty: true
    volumes:
      - "./app:/var/www/html"
    ports:
      - 8000:80

  mysql:
    image: mysql:5.7
    container_name: mysql_5.7
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: database
    ports:
      - "13306:3306"
